import DatabaseTypes
/// FieldSchema - Field-level type metadata for Persistable types
///
/// Provides compile-time metadata about each field's name, type, and stable field number.
/// Generated by `@Persistable` and consumed as validated schema catalog data.
/// Compiled model adaptation uses generated concrete field traversal.
///
/// **Design**: Analogous to PostgreSQL's `pg_attribute` catalog.

/// Schema metadata for a single field of a Persistable type
public struct FieldSchema: Sendable, Equatable, Hashable {
    /// Field name (e.g., "email", "price")
    public let name: String

    /// Stable field number (1-based, sequential)
    public let fieldNumber: Int

    /// Scalar type of the field
    public let type: FieldSchemaType

    /// Whether the field is Optional
    public let isOptional: Bool

    /// Whether the field is an Array
    public let isArray: Bool

    /// Canonical target entity for a typed reference field.
    public let referenceTargetEntity: String?

    /// Canonical value used when an older persisted row does not contain this
    /// field. `nil` means that the omission requires an explicit migration;
    /// `.some(.null)` is the distinct default for an optional field.
    public let defaultValue: FieldValue?

    public init(
        name: String,
        fieldNumber: Int,
        type: FieldSchemaType,
        isOptional: Bool = false,
        isArray: Bool = false,
        referenceTargetEntity: String? = nil,
        defaultValue: FieldValue? = nil
    ) {
        self.name = name
        self.fieldNumber = fieldNumber
        self.type = type
        self.isOptional = isOptional
        self.isArray = isArray
        self.referenceTargetEntity = referenceTargetEntity
        if let defaultValue {
            self.defaultValue = defaultValue
        } else if isOptional {
            self.defaultValue = FieldValue.null
        } else {
            self.defaultValue = nil
        }
    }
}

/// Scalar type classification for field schema
///
/// Maps Swift types to the canonical persisted value categories.
/// Used by model adapters to interpret values without a concrete property key path.
public enum FieldSchemaType: String, Sendable, Equatable, Hashable {
    case bool
    case int8
    case int16
    case int32
    case int64
    case uint8
    case uint16
    case uint32
    case uint64
    case float32
    case float64
    case decimal
    case string
    case bytes
    case date
    case time
    case dateTime
    case timestamp
    case timeSpan
    case calendarPeriod
    case geographicPoint
    case geographicPosition
    case vector
    case uuid
    case object
    case rdfTerm
    case reference
    /// Nested Persistable type represented as a `FieldObject`.
    case nested
    /// Enum type (encoded as varint or string depending on raw value)
    case `enum`
}

extension FieldSchemaType {
    /// Whether one canonical value of this field kind resolves to exactly one
    /// Directory path component.
    ///
    /// A dynamic Directory component is a single path element, so a kind is
    /// admitted only where the DatabaseFramework Directory bridge defines a
    /// total, injective textual form for it. That bridge owns the exact
    /// strings; this property owns which kinds have one, so a declaration no
    /// bridge can encode fails where it is written rather than at container
    /// bootstrap.
    ///
    /// `enum` is admitted in both of its raw representations because each one
    /// carries its own component tag.
    public var hasCanonicalDirectoryComponent: Bool {
        switch self {
        case .bool, .int8, .int16, .int32, .int64,
             .uint8, .uint16, .uint32, .uint64,
             .float32, .float64, .decimal,
             .string, .bytes,
             .date, .time, .dateTime, .timestamp, .timeSpan, .calendarPeriod,
             .geographicPoint, .geographicPosition,
             .uuid, .enum:
            return true
        case .vector, .object, .rdfTerm, .reference, .nested:
            return false
        }
    }
}
