import DatabaseTypes
/// FieldSchema - Field-level type metadata for Persistable types
///
/// Provides compile-time metadata about each field's name, type, and stable field number.
/// Generated by `@Persistable` macro. Used by schema registries and dynamic codecs
/// to decode/encode data without requiring the compiled `@Persistable` type.
///
/// **Design**: Analogous to PostgreSQL's `pg_attribute` catalog.

/// Schema metadata for a single field of a Persistable type
public struct FieldSchema: Sendable, Equatable, Hashable {
    /// Field name (e.g., "email", "price")
    public let name: String

    /// Stable field number (1-based, sequential)
    public let fieldNumber: Int

    /// Scalar type of the field
    public let type: FieldSchemaType

    /// Whether the field is Optional
    public let isOptional: Bool

    /// Whether the field is an Array
    public let isArray: Bool

    /// Canonical target entity for a typed reference field.
    public let referenceTargetEntity: String?

    public init(
        name: String,
        fieldNumber: Int,
        type: FieldSchemaType,
        isOptional: Bool = false,
        isArray: Bool = false,
        referenceTargetEntity: String? = nil
    ) {
        self.name = name
        self.fieldNumber = fieldNumber
        self.type = type
        self.isOptional = isOptional
        self.isArray = isArray
        self.referenceTargetEntity = referenceTargetEntity
    }
}

/// Scalar type classification for field schema
///
/// Maps Swift types to the canonical persisted value categories.
/// Used by model adapters to interpret values without a concrete property key path.
public enum FieldSchemaType: String, Sendable, Equatable, Hashable {
    case bool
    case int8
    case int16
    case int32
    case int64
    case uint8
    case uint16
    case uint32
    case uint64
    case float32
    case float64
    case decimal
    case string
    case bytes
    case date
    case time
    case dateTime
    case timestamp
    case timeSpan
    case calendarPeriod
    case geographicPoint
    case geographicPosition
    case vector
    case uuid
    case object
    case rdfTerm
    case reference
    /// Nested Persistable type represented as a `FieldObject`.
    case nested
    /// Enum type (encoded as varint or string depending on raw value)
    case `enum`

    /// Resolve field schema type at runtime for types the macro cannot classify at compile time.
    ///
    /// The `@Persistable` macro generates `FieldSchemaType.resolve(TypeName.self)` for
    /// non-primitive types. At runtime, this checks `RawRepresentable` conformance
    /// to distinguish enums from nested Persistable types.
    ///
    /// - Parameter type: The Swift type to classify
    /// - Returns: `.enum` if the type conforms to `RawRepresentable`, `.nested` otherwise
    public static func resolve(_ type: Any.Type) -> FieldSchemaType {
        if type is any PersistableReferenceValue.Type {
            return .reference
        }
        if type is any RawRepresentable.Type {
            return .enum
        }
        return .nested
    }
}
