// IndexDescriptor.swift
// FDBModel - Index descriptor (metadata)
//
// Provides declarative index definition using Swift KeyPaths.
// Used by macro generation, schema definition, and execution layer interpretation.

/// Index descriptor (metadata)
///
/// **Purpose**: Declarative index definition using KeyPaths
/// - Generated by macros (@Persistable)
/// - Used in schema definitions (Schema)
/// - Interpreted by execution layer (IndexMaintainer)
///
/// **Design principles**:
/// - Pure metadata (no execution logic)
/// - Type-safe KeyPath storage
/// - Refactoring-friendly (IDE renames propagate)
///
/// **Example**:
/// ```swift
/// @Persistable
/// struct User {
///     #Index<User>([\.email], unique: true)
///     #Index<User>([\.address.city])
///     #Index<User>([\.period.lowerBound])
///
///     var email: String
///     var address: Address
///     var period: Range<Date>
/// }
///
/// // Generated IndexDescriptors use KeyPaths directly:
/// // - [\User.email]
/// // - [\User.address.city]
/// // - [\User.period.lowerBound]
/// ```
public struct IndexDescriptor: Descriptor, Sendable {
    /// Index name (unique identifier)
    ///
    /// **Naming convention**: "{RecordType}_{field1}_{field2}_..."
    ///
    /// **Examples**:
    /// - "User_email"
    /// - "User_address_city"
    /// - "Product_category_price"
    ///
    /// **Note**: This name is used in FDB key space.
    /// Changing it breaks compatibility with existing data.
    public let name: String

    /// Index kind
    ///
    /// **Kind examples**:
    /// - Scalar: Standard B-tree index
    /// - Vector: HNSW similarity search
    /// - Count/Sum/Min/Max: Aggregation indexes
    ///
    /// **Example**:
    /// ```swift
    /// let kind: any IndexKind = ScalarIndexKind()
    /// ```
    public let kind: IndexKindMetadata

    /// Common options
    ///
    /// **Includes**:
    /// - unique: Uniqueness constraint
    /// - sparse: Exclude null values
    /// - metadata: User-defined metadata
    public let commonOptions: CommonIndexOptions

    /// Field names for indexed KeyPaths (resolved at construction time)
    ///
    /// **Benefits**:
    /// - Cached at construction (no repeated computation)
    /// - Used by QueryPlanner, IndexMaintainer for field matching
    ///
    /// **Example**: `["email"]`, `["category", "price"]`
    public let fieldNames: [String]

    /// Field names stored in the index value (for covering index / index-only scan)
    ///
    /// When a query only needs these fields plus the indexed fields,
    /// the executor can read values directly from the index without
    /// looking up the primary record.
    ///
    /// **Example**: `["name", "price"]`
    public let storedFieldNames: [String]

    /// Standard initializer with typed KeyPaths
    ///
    /// **Example**:
    /// ```swift
    /// let descriptor = IndexDescriptor(
    ///     name: "User_email",
    ///     keyPaths: [\User.email],
    ///     kind: ScalarIndexKind(),
    ///     commonOptions: .init(unique: true)
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - name: Index name (unique identifier)
    ///   - keyPaths: Array of KeyPaths to indexed fields
    ///   - kind: Index kind metadata
    ///   - commonOptions: Common options (default: empty)
    public init<Root: Persistable, Kind: IndexKind>(
        name: String,
        keyPaths: [PartialKeyPath<Root>],
        kind: borrowing Kind,
        commonOptions: CommonIndexOptions = .init(),
        storedFieldNames: [String] = []
    ) {
        self.name = name
        self.fieldNames = keyPaths.map { Root.fieldName(for: $0) }
        self.kind = IndexKindMetadata(kind)
        self.commonOptions = commonOptions
        self.storedFieldNames = storedFieldNames
    }

    /// Creates a descriptor from canonical index metadata while preserving
    /// compile-time validation of the indexed key paths.
    public init<Root: Persistable>(
        name: String,
        keyPaths: [PartialKeyPath<Root>],
        kind: IndexKindMetadata,
        commonOptions: CommonIndexOptions = .init(),
        storedFieldNames: [String] = []
    ) {
        self.name = name
        self.fieldNames = keyPaths.map { Root.fieldName(for: $0) }
        self.kind = kind
        self.commonOptions = commonOptions
        self.storedFieldNames = storedFieldNames
    }

}

// MARK: - Convenience Methods

extension IndexDescriptor {
    /// Whether index has uniqueness constraint
    ///
    /// **Example**:
    /// ```swift
    /// if descriptor.isUnique {
    ///     print("This is a unique index")
    /// }
    /// ```
    public var isUnique: Bool {
        commonOptions.unique
    }

    /// Whether index is sparse
    ///
    /// **Example**:
    /// ```swift
    /// if descriptor.isSparse {
    ///     print("This is a sparse index (null values excluded)")
    /// }
    /// ```
    public var isSparse: Bool {
        commonOptions.sparse
    }

    /// Index kind identifier
    ///
    /// **Example**:
    /// ```swift
    /// switch descriptor.kindIdentifier {
    /// case "scalar":
    ///     print("Scalar index")
    /// case "vector":
    ///     print("Vector index")
    /// default:
    ///     print("Unknown index kind: \(descriptor.kindIdentifier)")
    /// }
    /// ```
    public var kindIdentifier: String {
        kind.identifier
    }

    /// Whether this index supports index-only scan (covering index)
    ///
    /// An index is covering when it stores additional fields in its value,
    /// allowing queries to be answered without looking up the primary record.
    public var isCovering: Bool {
        !storedFieldNames.isEmpty
    }
}

// MARK: - Description

// MARK: - Hashable

extension IndexDescriptor: Hashable {
    public static func == (lhs: IndexDescriptor, rhs: IndexDescriptor) -> Bool {
        lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
    }
}

// MARK: - Description

extension IndexDescriptor: CustomStringConvertible {
    public var description: String {
        var parts = [
            "IndexDescriptor(name: \(name)",
            "kind: \(kind.identifier)",
            "fields: [\(fieldNames.joined(separator: ", "))]"
        ]

        if isUnique {
            parts.append("unique: true")
        }

        if isSparse {
            parts.append("sparse: true")
        }

        if !commonOptions.metadata.isEmpty {
            parts.append("metadata: \(commonOptions.metadata)")
        }

        return parts.joined(separator: ", ") + ")"
    }
}
