import Core

/// Protocol for Persistable types bound to an OWL class.
///
/// Conformance is auto-generated by the `@OWLClass` macro.
/// `ontologyClassIRI` corresponds to an OWL class IRI in the OntologyStore.
public protocol OWLClassEntity: Persistable, _OWLClassIRIProvider, _DataPropertyIRIsProvider {
    static var ontologyClassIRI: String { get }
    static var ontologyPropertyDescriptors: [OWLDataPropertyDescriptor] { get }

    /// OWL triple index descriptors, generated by `@OWLClass` macro.
    ///
    /// Contains an `OWLTripleIndexKind` IndexDescriptor that enables
    /// automatic entity-to-triple materialization via OntologyIndex.
    static var _owlTripleDescriptors: [any Descriptor] { get }
}

extension OWLClassEntity {
    public static var dataPropertyIRIs: [String] {
        ontologyPropertyDescriptors.map(\.iri)
    }
}

/// Merge `_persistableDescriptors` (from @Persistable) with `_owlTripleDescriptors` (from @OWLClass).
///
/// This constrained extension takes priority over the default `Persistable.descriptors`
/// when the type conforms to `OWLClassEntity`, thanks to Swift protocol extension priority rules.
extension Persistable where Self: OWLClassEntity {
    public static var descriptors: [any Descriptor] {
        _persistableDescriptors + _owlTripleDescriptors
    }
}

/// Backward compatibility
public typealias OntologyEntity = OWLClassEntity
