import Core

/// Protocol for Persistable types bound to an OWL class.
///
/// Conformance is auto-generated by the `@OWLClass` macro.
/// `ontologyClassIRI` corresponds to an OWL class IRI in the OntologyStore.
public protocol OWLClassEntity: Persistable, _OntologyClassIRIProvider {
    static var ontologyClassIRI: String { get }
    static var ontologyPropertyDescriptors: [OWLDataPropertyDescriptor] { get }
}

/// Backward compatibility
public typealias OntologyEntity = OWLClassEntity
