import Core

/// Metadata descriptor for an OWL DatatypeProperty field.
///
/// Auto-generated by the `@OWLClass` / `@OWLObjectProperty` macro
/// from `@OWLDataProperty` annotations.
/// Follows the same `Descriptor` pattern as `RelationshipDescriptor`.
public struct OWLDataPropertyDescriptor: Descriptor, Sendable, Codable, Hashable {

    /// Descriptor name (`{TypeName}_{fieldName}` format)
    public let name: String

    /// Field name (Swift property name)
    public let fieldName: String

    /// OWL property IRI
    public let iri: String

    /// Display label (falls back to IRI local name if nil)
    public let label: String?

    /// Target type name (non-nil for ObjectProperty references, nil for DataProperty)
    public let targetTypeName: String?

    /// Target type reverse-lookup field name (from `to:` parameter)
    public let targetFieldName: String?

    /// Whether this is an ObjectProperty reference (`targetTypeName != nil`)
    public var isObjectProperty: Bool { targetTypeName != nil }

    public init(
        name: String,
        fieldName: String,
        iri: String,
        label: String? = nil,
        targetTypeName: String? = nil,
        targetFieldName: String? = nil
    ) {
        self.name = name
        self.fieldName = fieldName
        self.iri = iri
        self.label = label
        self.targetTypeName = targetTypeName
        self.targetFieldName = targetFieldName
    }
}

/// Backward compatibility
public typealias OntologyPropertyDescriptor = OWLDataPropertyDescriptor
