import Core

/// Protocol for Persistable types that materialize an OWL ObjectProperty.
///
/// Conformance is auto-generated by the `@OWLObjectProperty` macro.
/// The type represents a reified relationship with `from` and `to` endpoints.
public protocol OWLObjectPropertyEntity: Persistable, _OWLObjectPropertyIRIProvider, _DataPropertyIRIsProvider {
    static var objectPropertyIRI: String { get }
    static var fromFieldName: String { get }
    static var toFieldName: String { get }
    static var ontologyPropertyDescriptors: [OWLDataPropertyDescriptor] { get }
}

extension OWLObjectPropertyEntity {
    public static var dataPropertyIRIs: [String] {
        ontologyPropertyDescriptors.map(\.iri)
    }
}
