import Core

/// Metadata descriptor for an OWL ObjectProperty entity.
///
/// Auto-generated by `@Persistable` when `@OWLObjectProperty` is detected.
/// Captures the ObjectProperty IRI and its from/to endpoint field names.
public struct OWLObjectPropertyDescriptor: Descriptor, Sendable, Codable, Hashable {

    /// Descriptor name (`{TypeName}_objectProperty` format)
    public let name: String

    /// OWL ObjectProperty IRI
    public let iri: String

    /// Source endpoint field name
    public let fromFieldName: String

    /// Target endpoint field name
    public let toFieldName: String

    public init(
        name: String,
        iri: String,
        fromFieldName: String,
        toFieldName: String
    ) {
        self.name = name
        self.iri = iri
        self.fromFieldName = fromFieldName
        self.toFieldName = toFieldName
    }
}

/// Type-safe accessor for OWLObjectPropertyDescriptor
extension Persistable {
    public static var owlObjectPropertyDescriptors: [OWLObjectPropertyDescriptor] {
        descriptors.compactMap { $0 as? OWLObjectPropertyDescriptor }
    }
}
