/// Macro that binds a Persistable type to an OWL ObjectProperty,
/// materializing a relationship as a first-class entity.
///
/// Declares `from` and `to` fields that represent the relationship endpoints.
/// `@Persistable` automatically generates a graph index for these fields.
///
/// **Usage**:
/// ```swift
/// @Persistable
/// @OWLObjectProperty("onto:employs", from: "employeeID", to: "projectID")
/// struct Assignment {
///     var id: String = UUID().uuidString
///     var employeeID: String = ""
///     var projectID: String = ""
///
///     @OWLDataProperty("onto:since")
///     var startDate: Date = Date()
/// }
/// ```
///
/// **Generated code**:
/// - `static var objectPropertyIRI: String` — OWL ObjectProperty IRI
/// - `static var fromFieldName: String` — source field name
/// - `static var toFieldName: String` — target field name
/// - `static var ontologyPropertyDescriptors: [OWLDataPropertyDescriptor]` — metadata for `@OWLDataProperty` fields
/// - `OWLObjectPropertyEntity` protocol conformance
/// - Graph index descriptor (auto-generated by `@Persistable`)
@attached(member, names: named(objectPropertyIRI), named(fromFieldName), named(toFieldName), named(ontologyPropertyDescriptors))
@attached(extension, conformances: OWLObjectPropertyEntity)
public macro OWLObjectProperty(
    _ iri: String,
    from: String,
    to: String
) = #externalMacro(module: "GraphMacros", type: "OWLObjectPropertyMacro")
