// RestrictedFieldMetadata.swift
// Core - Static metadata for restricted fields

import Foundation

/// Static metadata about a restricted field
///
/// This struct is generated by `@Persistable` macro for each `@Restricted` field.
/// It provides compile-time metadata that doesn't change after decode, unlike
/// the `Restricted` property wrapper's instance data.
///
/// **Generated by macro**:
/// ```swift
/// @Persistable
/// struct Employee {
///     @Restricted(read: .roles(["hr"]), write: .roles(["hr"]))
///     var salary: Double = 0
/// }
///
/// // Generates:
/// public static var restrictedFieldsMetadata: [RestrictedFieldMetadata] {
///     [
///         RestrictedFieldMetadata(
///             fieldName: "salary",
///             readAccess: .roles(["hr"]),
///             writeAccess: .roles(["hr"])
///         )
///     ]
/// }
/// ```
public struct RestrictedFieldMetadata: Sendable, Equatable {
    /// Name of the restricted field
    public let fieldName: String

    /// Read access level
    public let readAccess: FieldAccessLevel

    /// Write access level
    public let writeAccess: FieldAccessLevel

    public init(
        fieldName: String,
        readAccess: FieldAccessLevel,
        writeAccess: FieldAccessLevel
    ) {
        self.fieldName = fieldName
        self.readAccess = readAccess
        self.writeAccess = writeAccess
    }
}
