import DatabaseTypes

/// Protocol for Persistable types bound to an OWL class.
///
/// Conformance is auto-generated by the `@OWLClass` macro.
/// `ontologyClassIRI` corresponds to an OWL class IRI in the OntologyStore.
public protocol OWLClassEntity: Persistable {
    static var ontologyClassIRI: String { get }
    static var ontologyPropertyDescriptors: [OWLDataPropertyDescriptor] { get }
    static var ontologyIndividualIRIBase: String { get }
    static var ontologyGraph: RDFGraphName? { get }

    func ontologySubject() throws(OWLProjectionError) -> RDFSubject
    func ontologyQuads() throws(OWLProjectionError) -> [RDFQuad]

    /// OWL RDF index descriptors without dynamic type recovery.
    static var _owlRDFIndexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError)
    }
}

extension OWLClassEntity {
    public static var dataPropertyIRIs: [String] {
        ontologyPropertyDescriptors.map { $0.iri }
    }

    public static var ontologyBinding: OntologyBinding? {
        .owlClass(
            iri: ontologyClassIRI,
            dataPropertyIRIs: dataPropertyIRIs
        )
    }
}

extension Persistable where Self: OWLClassEntity {
    public static var indexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError) {
            try _persistableIndexDescriptors + _owlRDFIndexDescriptors
        }
    }
}
