import DatabaseTypes

/// Protocol for Persistable types bound to an OWL class.
///
/// Conformance is auto-generated by the `@OWLClass` macro.
/// `ontologyClassIRI` corresponds to an OWL class IRI in the OntologyStore.
public protocol OWLClassEntity: Persistable, _OWLClassIRIProvider, _DataPropertyIRIsProvider {
    static var ontologyClassIRI: String { get }
    static var ontologyPropertyDescriptors: [OWLDataPropertyDescriptor] { get }
    static var ontologyIndividualIRIBase: String { get }
    static var ontologyGraph: RDFGraphName? { get }

    func ontologySubject() throws -> RDFSubject
    func ontologyQuads() throws -> [RDFQuad]

    /// OWL RDF projection descriptors generated by the `@OWLClass` macro.
    ///
    /// Contains an `OWLClassRDFIndexKind` descriptor that enables canonical
    /// entity-to-RDF materialization via OntologyIndex.
    static var _owlRDFDescriptors: [any Descriptor] {
        get throws(IndexDeclarationError)
    }

    /// OWL RDF index descriptors without dynamic type recovery.
    static var _owlRDFIndexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError)
    }
}

extension OWLClassEntity {
    public static var dataPropertyIRIs: [String] {
        ontologyPropertyDescriptors.map { $0.iri }
    }
}

/// Merge persistable descriptors with the RDF projection declared by `@OWLClass`.
///
/// This constrained extension takes priority over the default `Persistable.descriptors`
/// when the type conforms to `OWLClassEntity`, thanks to Swift protocol extension priority rules.
extension Persistable where Self: OWLClassEntity {
    public static var descriptors: [any Descriptor] {
        get throws(IndexDeclarationError) {
            try _persistableDescriptors + _owlRDFDescriptors
        }
    }

    public static var indexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError) {
            try _persistableIndexDescriptors + _owlRDFIndexDescriptors
        }
    }
}
