import DatabaseTypes

/// Persistable protocol - Storage-independent persistable model interface
///
/// This protocol defines the metadata and serialization interface for persistable data models.
/// It is storage-independent and can be used across all data model layers:
/// - Entity layer (RDB-like): Structured entities
/// - DocumentLayer (Document store): Flexible documents
/// - VectorLayer (Vector search): Vector embeddings with similarity search
/// - GraphLayer (Graph database): Nodes and edges with relationships
///
/// **Platform Support**:
/// - Client: Model definitions and metadata
/// - Runtime: Full persistence through database-framework
///
/// **Implementation**: Generated by @Persistable macro
///
/// **Usage**:
/// ```swift
/// @Persistable
/// struct User {
///     var id: String
///
///     #Directory<User>("users")
///     #Index(.scalar, fields: [\User.email], unique: true)
///
///     var email: String
///     var name: String
/// }
/// ```
///
/// **Generated Properties**:
/// - `persistableType`: Type identifier (e.g., "User")
/// - `allFields`: All field names
/// - `indexDescriptors`: Index metadata
///
@dynamicMemberLookup
public protocol Persistable: FieldValueEncodable {
    // MARK: - ID

    /// The type of the unique identifier
    ///
    /// The identifier must provide one canonical logical representation through
    /// `PersistableIdentifier`. Storage and DatabaseWire use that same representation,
    /// so identifier support is enforced at compile time instead of by a runtime
    /// cast in a storage adapter.
    ///
    /// **Supported scalar ID types**:
    /// - `String` (recommended: ULID for sortable unique IDs)
    /// - `Int64`, `Int32`, `Int16`, `Int8`, `Int`
    /// - `UInt64`, `UInt32`, `UInt16`, `UInt8`, `UInt`
    /// - `UUID`
    /// - `Bool`
    /// - `ByteString`, `[UInt8]`
    ///
    /// Custom composite identifiers conform to `PersistableIdentifier` and declare an
    /// exact `PersistableIdentifierType.composite` shape.
    associatedtype ID: PersistableIdentifier

    /// Unique identifier for this instance
    ///
    /// The application declares this field and chooses its generation policy.
    /// Macro-generated initializers include it unless the declaration supplies
    /// a default value.
    var id: ID { get }

    /// Canonical identifier shape exposed to schema and wire declarations.
    static var persistableIdentifierType: PersistableIdentifierType { get }

    /// Canonical identifier value used by references and persisted identities.
    var persistableIdentifierValue: ReferenceIdentifier { get }

    // MARK: - Metadata (Storage-independent)

    /// Type identifier for this persistable type
    ///
    /// This is the canonical name used across all layers to identify the type.
    /// Can be customized via `@Persistable(type: "CustomName")`.
    ///
    /// **Examples**:
    /// - Default: struct name (e.g., "User", "Product")
    /// - Custom: `@Persistable(type: "User")` on a `Member` struct
    static var persistableType: String { get }

    /// All field names in the persistable type
    ///
    /// Includes all stored properties (including `id`), in declaration order.
    ///
    /// **Example**: `["id", "email", "name", "createdAt"]`
    static var allFields: [String] { get }

    /// Macro-generated index descriptors without dynamic type recovery.
    static var _persistableIndexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError)
    }

    /// Validated index declarations for this model.
    ///
    /// Index metadata remains homogeneous so Embedded consumers never need
    /// existential storage or runtime type recovery.
    static var indexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError)
    }

    /// Typed relationship declarations for this model.
    static var relationshipDescriptors: [RelationshipDescriptor] { get }

    /// Ontology role compiled for this model, when one is declared.
    static var ontologyBinding: OntologyBinding? { get }

    /// Polymorphic group membership inherited by this concrete model.
    static var polymorphicMembership: PolymorphicMembership? { get }

    /// Complete static schema declaration for this model.
    static var schemaEntity: Schema.Entity {
        get throws(SchemaEntityError)
    }

    // MARK: - Directory Metadata

    /// Logical directory path components for persisted storage.
    ///
    /// Generated from `#Directory<T>` macro declarations.
    /// Contains canonical static path and dynamic field components.
    ///
    /// **Example**:
    /// ```swift
    /// #Directory<User>("app", "users")
    /// // → [.staticPath("app"), .staticPath("users")]
    ///
    /// #Directory<Order>("tenants", \Order.tenantID, "orders")
    /// // → [.staticPath("tenants"), .dynamicField("tenantID"), .staticPath("orders")]
    /// ```
    ///
    /// **Default**: Returns `[.staticPath(persistableType)]` if not specified via macro.
    static var directoryPathComponents: [DirectoryPathComponent] { get }

    /// Logical directory resolution policy.
    ///
    /// Generated from `#Directory<T>` macro's `layer:` parameter.
    ///
    /// **Example**:
    /// ```swift
    /// #Directory<User>("app", "users")
    /// // → .default
    ///
    /// #Directory<Order>("tenants", \Order.tenantID, "orders", layer: .partition)
    /// // → .partition
    /// ```
    ///
    /// **Default**: `.default` if not specified via macro.
    static var directoryLayer: DirectoryLayer { get }

    /// Field-level type metadata for all persisted fields
    ///
    /// Provides name, stable field number, type, optionality, and array status
    /// for each field. Schema registries consume it as immutable catalog data;
    /// compiled adaptation uses generated concrete field traversal.
    ///
    /// **Implementation**: Generated by @Persistable macro
    ///
    /// **Example**:
    /// ```swift
    /// @Persistable
    /// struct User {
    ///     var email: String
    ///     var age: Int32 = 0
    /// }
    ///
    /// User.fieldSchemas
    /// // [FieldSchema(name: "id", fieldNumber: 1, type: .string, ...),
    /// //  FieldSchema(name: "email", fieldNumber: 2, type: .string, ...),
    /// //  FieldSchema(name: "age", fieldNumber: 3, type: .int32, ...)]
    /// ```
    static var fieldSchemas: [FieldSchema] { get }

    /// Reconstruct a compiled persistable directly from canonical database values.
    static func decodePersistedFields(_ fields: [PersistableField]) throws -> Self

    /// Traverse this compiled model into a concrete typed field destination.
    func encodePersistedFields<Output: PersistedFieldOutput>(
        to output: inout Output
    ) throws(PersistableEncodingFailure<Output.Failure>)

    /// Reconstruct a nested model from a primitive object representation.
    static func decodePersistedObject(_ object: FieldObject) throws -> Self

    /// Get the stable field number for a field name.
    ///
    /// Used by serialization layers that require stable field numbering.
    ///
    /// - Parameter fieldName: The field name
    /// - Returns: Field number, or nil if field doesn't exist or numbering is not defined
    static func fieldNumber(for fieldName: String) -> Int?

    /// Get enum metadata for a field (if the field is an enum)
    ///
    /// Provides enum case information for validation and serialization.
    ///
    /// - Parameter fieldName: The field name
    /// - Returns: EnumMetadata if field is an enum, nil otherwise
    static func enumMetadata(for fieldName: String) -> EnumMetadata?

    // MARK: - Field-Level Security

    /// Static metadata about fields marked with `@Restricted`
    ///
    /// Generated by `@Persistable` macro for each `@Restricted` field.
    /// This metadata is compile-time constant and does not change after decode.
    ///
    /// **Usage**:
    /// ```swift
    /// @Persistable
    /// struct Employee {
    ///     @Restricted(read: .roles(["hr"]), write: .roles(["hr"]))
    ///     var salary: Double = 0
    /// }
    ///
    /// // Access static metadata
    /// let metadata = Employee.restrictedFieldsMetadata
    /// // → [RestrictedFieldMetadata(fieldName: "salary", readAccess: .roles(["hr"]), ...)]
    /// ```
    static var restrictedFieldsMetadata: [RestrictedFieldMetadata] { get }

    /// Create a copy with restricted fields masked to default values
    ///
    /// Generated by `@Persistable` macro. Fields that the auth context cannot read
    /// are replaced with their type's default values.
    ///
    /// **Usage**:
    /// ```swift
    /// let employee = Employee(name: "Alice", salary: 100000)
    /// let regularUserAuth = TestAuth(userID: "user1", roles: ["employee"])
    ///
    /// let masked = employee.masked(auth: regularUserAuth)
    /// // masked.salary == 0 (default value, because user lacks "hr" role)
    /// // masked.name == "Alice" (unchanged)
    /// ```
    ///
    /// - Parameter auth: Authentication context (nil = unauthenticated)
    /// - Returns: Copy with restricted fields masked
    func masked(auth: (any AuthContext)?) -> Self

    // MARK: - Dynamic Field Access

    /// Access field values dynamically by name
    ///
    /// Enables runtime field access using string-based field names.
    /// This is used by DataAccess for KeyExpression evaluation and index building.
    ///
    /// **Implementation**: Generated by @Persistable macro
    ///
    /// **Example**:
    /// ```swift
    /// @Persistable
    /// struct User {
    ///     var email: String
    /// }
    ///
    /// let user = User(email: "user@example.com")
    /// let email = user[dynamicMember: "email"]  // Optional<any Sendable>
    /// ```
    ///
    /// - Parameter member: Field name to access
    /// - Returns: Field value as Sendable, or nil if field doesn't exist
    subscript(dynamicMember member: String) -> (any Sendable)? { get }

}

// MARK: - Default Implementations

public extension Persistable {
    static var fieldSchemaType: FieldSchemaType { .nested }

    func encodeFieldValue() throws(PersistableEncodingError) -> FieldValue {
        try PersistableFieldEncoder.object(from: self)
    }

    static var persistableIdentifierType: PersistableIdentifierType {
        ID.persistableIdentifierType
    }

    var persistableIdentifierValue: ReferenceIdentifier {
        id.persistableIdentifierValue
    }

    /// Default: no macro-generated indexes.
    static var _persistableIndexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError) { [] }
    }

    /// Default index declarations contain only those emitted by `@Persistable`.
    static var indexDescriptors: [IndexDescriptor] {
        get throws(IndexDeclarationError) {
            try _persistableIndexDescriptors
        }
    }

    /// Default: no relationships.
    static var relationshipDescriptors: [RelationshipDescriptor] { [] }

    /// Default: the model has no ontology role.
    static var ontologyBinding: OntologyBinding? { nil }

    /// Default: the model is not part of a polymorphic group.
    static var polymorphicMembership: PolymorphicMembership? { nil }

    static var schemaEntity: Schema.Entity {
        get throws(SchemaEntityError) {
            try Schema.Entity(from: Self.self)
        }
    }

    /// Default implementation uses persistableType as single path component
    ///
    /// If `#Directory` macro is not used, defaults to `[.staticPath(persistableType)]`.
    /// For example, `User` type → directory path `["User"]`.
    ///
    /// **Note**: @Persistable macro always generates explicit implementations,
    /// which override this default for macro-decorated types.
    static var directoryPathComponents: [DirectoryPathComponent] {
        [.staticPath(persistableType)]
    }

    /// Default implementation returns `.default` layer
    ///
    /// If `#Directory` macro is not used, defaults to `.default` layer.
    ///
    /// **Note**: @Persistable macro always generates explicit implementations,
    /// which override this default for macro-decorated types.
    static var directoryLayer: DirectoryLayer { .default }

    /// Default implementation returns empty array (no field schemas)
    static var fieldSchemas: [FieldSchema] { [] }

    static func decodePersistedFields(_ fields: [PersistableField]) throws -> Self {
        throw PersistableDecodingError.missingCompiledDecoder(
            persistableType
        )
    }

    func encodePersistedFields<Output: PersistedFieldOutput>(
        to output: inout Output
    ) throws(PersistableEncodingFailure<Output.Failure>) {
        throw .adaptation(.missingCompiledEncoder(Self.persistableType))
    }

    static func decodePersistedObject(_ object: FieldObject) throws -> Self {
        var schemasByName: [String: FieldSchema] = [:]
        for schema in fieldSchemas {
            guard schemasByName.updateValue(
                schema,
                forKey: schema.name
            ) == nil else {
                throw PersistableDecodingError.duplicateSchemaFieldName(
                    schema.name
                )
            }
        }

        var fields: [PersistableField] = []
        fields.reserveCapacity(object.count)
        for field in object.fields {
            guard let schema = schemasByName[field.key],
                  let number = UInt32(exactly: schema.fieldNumber) else {
                throw PersistableDecodingError.unknownField(
                    number: 0,
                    name: field.key
                )
            }
            fields.append(
                try PersistableField(
                    number: number,
                    name: field.key,
                    value: field.value
                )
            )
        }
        return try decodePersistedFields(fields)
    }

    /// Default implementation returns nil (no field numbers)
    static func fieldNumber(for fieldName: String) -> Int? { nil }

    /// Default implementation returns nil (no enum metadata)
    static func enumMetadata(for fieldName: String) -> EnumMetadata? { nil }

    /// Default implementation returns empty array (no restricted fields)
    static var restrictedFieldsMetadata: [RestrictedFieldMetadata] { [] }

    /// Default implementation returns self unchanged (no masking)
    func masked(auth: (any AuthContext)?) -> Self { self }

}
