import DatabaseTypes
// IndexDescriptor.swift
// Database index descriptor metadata.
//
// Provides validated, key-path-free index metadata.
// Used by macro generation, schema definition, and execution layer interpretation.

/// Index descriptor (metadata)
///
/// **Purpose**: Validated declarative index metadata
/// - Generated by macros (@Persistable)
/// - Used in schema definitions (Schema)
/// - Interpreted by execution layer (IndexMaintainer)
///
/// **Design principles**:
/// - Pure metadata (no execution logic)
/// - Stable field identity and ordering
/// - No retained runtime KeyPaths
///
/// **Example**:
/// ```swift
/// @Persistable
/// struct User {
///     #Index(.scalar, fields: [\User.email], unique: true)
///
///     var email: String
/// }
/// ```
public struct IndexDescriptor: Descriptor, Sendable {
    /// Index name (unique identifier)
    ///
    /// **Naming convention**: "{EntityType}_{field1}_{field2}_..."
    ///
    /// **Examples**:
    /// - "User_email"
    /// - "User_address_city"
    /// - "Product_category_price"
    ///
    /// **Note**: This name identifies persisted index state.
    /// Changing it breaks compatibility with existing data.
    public let name: String

    /// Index kind
    ///
    /// **Kind examples**:
    /// - Scalar: Standard B-tree index
    /// - Vector: HNSW similarity search
    /// - Count/Sum/Min/Max: Aggregation indexes
    ///
    public let kind: IndexKindMetadata

    /// Common options
    ///
    /// **Includes**:
    /// - unique: Uniqueness constraint
    /// - sparse: Exclude null values
    /// - metadata: User-defined metadata
    public let commonOptions: CommonIndexOptions

    /// Names of indexed persisted fields.
    ///
    /// **Benefits**:
    /// - Cached at construction (no repeated computation)
    /// - Used by QueryPlanner, IndexMaintainer for field matching
    ///
    /// **Example**: `["email"]`, `["category", "price"]`
    public let fieldNames: [String]

    /// Field names stored in the index value (for covering index / index-only scan)
    ///
    /// When a query only needs these fields plus the indexed fields,
    /// the executor can read values directly from the index without
    /// looking up the primary entity.
    ///
    /// **Example**: `["name", "price"]`
    public let storedFieldNames: [String]

    /// Creates a descriptor from a typed custom index kind.
    ///
    /// **Example**:
    /// ```swift
    /// let descriptor = IndexDescriptor(
    ///     name: "User_email",
    ///     kind: TimeSeriesIndexKind<User>(
    ///         field: User.fields.createdAt.ascending
    ///     ),
    ///     commonOptions: .init(unique: true)
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - name: Index name (unique identifier)
    ///   - kind: Index kind metadata
    ///   - commonOptions: Common options (default: empty)
    public init<Kind: IndexKind>(
        name: String,
        kind: borrowing Kind,
        commonOptions: CommonIndexOptions = .init(),
        storedFields: [IndexField<Kind.Model>] = []
    ) throws(IndexDeclarationError) {
        var fieldsByNumber: [Int: FieldSchema] = [:]
        for field in Kind.Model.fieldSchemas {
            fieldsByNumber[field.fieldNumber] = field
        }
        var fields: [FieldSchema] = []
        fields.reserveCapacity(kind.indexFields.count)
        for selectedField in kind.indexFields {
            guard
                let field = fieldsByNumber[selectedField.identity.number],
                field.name == selectedField.identity.name
            else {
                throw IndexDeclarationError(
                    indexName: name,
                    validationError: .invalidConfiguration(
                        index: Kind.identifier,
                        reason: "Field identity '\(selectedField.name)#\(selectedField.identity.number)' is absent from the static schema"
                    )
                )
            }
            fields.append(field)
        }
        for storedField in storedFields {
            guard
                let field = fieldsByNumber[storedField.identity.number],
                field.name == storedField.identity.name
            else {
                throw IndexDeclarationError(
                    indexName: name,
                    validationError: .invalidConfiguration(
                        index: Kind.identifier,
                        reason: "Stored field identity '\(storedField.name)#\(storedField.identity.number)' is absent from the static schema"
                    )
                )
            }
        }
        do {
            try Kind.validateFields(fields)
            try kind.validateConfiguration()
        } catch let validationError {
            throw IndexDeclarationError(
                indexName: name,
                validationError: validationError
            )
        }

        self.name = name
        self.fieldNames = kind.fieldNames
        self.kind = IndexKindMetadata(kind)
        self.commonOptions = commonOptions
        self.storedFieldNames = storedFields.map { $0.name }
    }

    /// Creates a built-in descriptor from the canonical declaration semantics
    /// emitted by `#Index`.
    public init<Model: Persistable>(
        name: String,
        definition: IndexDefinition,
        fields: [IndexField<Model>],
        commonOptions: CommonIndexOptions = .init(),
        storedFields: [IndexField<Model>] = []
    ) throws(IndexDeclarationError) {
        var fieldsByNumber: [Int: FieldSchema] = [:]
        for field in Model.fieldSchemas {
            fieldsByNumber[field.fieldNumber] = field
        }

        var resolvedSchemas: [FieldSchema] = []
        resolvedSchemas.reserveCapacity(fields.count)
        for selectedField in fields {
            guard
                let schema = fieldsByNumber[selectedField.identity.number],
                schema.name == selectedField.identity.name
            else {
                throw IndexDeclarationError(
                    indexName: name,
                    validationError: .invalidConfiguration(
                        index: definition.identifier,
                        reason: "Field identity '\(selectedField.name)#\(selectedField.identity.number)' is absent from the static schema"
                    )
                )
            }
            resolvedSchemas.append(schema)
        }

        for storedField in storedFields {
            guard
                let schema = fieldsByNumber[storedField.identity.number],
                schema.name == storedField.identity.name
            else {
                throw IndexDeclarationError(
                    indexName: name,
                    validationError: .invalidConfiguration(
                        index: definition.identifier,
                        reason: "Stored field identity '\(storedField.name)#\(storedField.identity.number)' is absent from the static schema"
                    )
                )
            }
        }

        do {
            self.name = name
            self.kind = try definition.kindMetadata(
                fields: fields.map { $0.metadata },
                schemas: resolvedSchemas
            )
            self.commonOptions = commonOptions
            self.fieldNames = fields.map { $0.name }
            self.storedFieldNames = storedFields.map { $0.name }
        } catch let validationError {
            throw IndexDeclarationError(
                indexName: name,
                validationError: validationError
            )
        }
    }

    package init(validatedMetadata metadata: IndexDescriptorMetadata) {
        self.name = metadata.name
        self.kind = metadata.kind
        self.commonOptions = metadata.commonOptions
        self.fieldNames = metadata.fieldNames
        self.storedFieldNames = metadata.storedFieldNames
    }
}

// MARK: - Convenience Methods

extension IndexDescriptor {
    /// Whether index has uniqueness constraint
    ///
    /// **Example**:
    /// ```swift
    /// if descriptor.isUnique {
    ///     print("This is a unique index")
    /// }
    /// ```
    public var isUnique: Bool {
        commonOptions.unique
    }

    /// Whether index is sparse
    ///
    /// **Example**:
    /// ```swift
    /// if descriptor.isSparse {
    ///     print("This is a sparse index (null values excluded)")
    /// }
    /// ```
    public var isSparse: Bool {
        commonOptions.sparse
    }

    /// Index kind identifier
    ///
    /// **Example**:
    /// ```swift
    /// switch descriptor.kindIdentifier {
    /// case "scalar":
    ///     print("Scalar index")
    /// case "vector":
    ///     print("Vector index")
    /// default:
    ///     print("Unknown index kind: \(descriptor.kindIdentifier)")
    /// }
    /// ```
    public var kindIdentifier: String {
        kind.identifier
    }

    /// Whether this index supports index-only scan (covering index)
    ///
    /// An index is covering when it stores additional fields in its value,
    /// allowing queries to be answered without looking up the primary entity.
    public var isCovering: Bool {
        !storedFieldNames.isEmpty
    }
}

// MARK: - Description

// MARK: - Hashable

extension IndexDescriptor: Hashable {
    public static func == (lhs: IndexDescriptor, rhs: IndexDescriptor) -> Bool {
        lhs.name == rhs.name
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
    }
}

// MARK: - Description

extension IndexDescriptor: CustomStringConvertible {
    public var description: String {
        var parts = [
            "IndexDescriptor(name: \(name)",
            "kind: \(kind.identifier)",
            "fields: [\(fieldNames.joined(separator: ", "))]"
        ]

        if isUnique {
            parts.append("unique: true")
        }

        if isSparse {
            parts.append("sparse: true")
        }

        if !commonOptions.metadata.isEmpty {
            parts.append("metadata: \(commonOptions.metadata)")
        }

        return parts.joined(separator: ", ") + ")"
    }
}
